back up database

diff --git a/ncupgrade b/ncupgrade
--- a/ncupgrade
+++ b/ncupgrade
@@ -116,11 +116,122 @@ maintenance_mode() {
 create_temp_dir() {
 # creates a temporary directory
 
+  # create timestamp to append to backups:
+  now=$(date +"%Y.%m.%d-%H.%M")
+
   echo "+  creating temporary directory"
-  mkdir -p /tmp/ncupgrade
-  cd /tmp/ncupgrade
+
+  # store temp-directory in variable:
+  temp_dir="/tmp/ncupgrade"
+
+  mkdir -p "${temp_dir}"
+  cd "${temp_dir}"
+
   # remove eventually existing files from previous run of this script (suppress error, if nothing is there to be removed):
   rm -r * > /dev/null 2>&1
+}
+
+create_backup_dir() {
+# creates backup directory if not yet existing:
+
+  mkdir -p "${backup_dir}"
+}
+
+get_nc_config_value() {
+# reads value ($1) from Nextclouds system configuration
+
+  local value
+
+  value="$(sudo -u ${htuser} php "${nextcloud_dir}/occ" --no-warnings config:system:get ${1})"
+  echo "${value}"
+}
+
+compress_move_backup() {
+# compresses backed up and moves compressed backup to backup folder
+# arguments:
+#       $1 - file to be compressed and moved (needs to be presend in $temp_dir
+
+  # compress backup using the configured method (zip or tar.gz):
+  if [[ "${compression_method}" == "zip" ]]; then
+    # use zip to compress folder with backed up files:
+    zip -r -q "${1}.zip" "${1}"
+    # store error, to be able to print error message:
+    [[ $? -eq 0 ]] || compress_error="1"
+  else
+    # use "tar.gz" as compression_method, in case invalid value was entered:
+    compression_method="tar.gz"
+    # use tar.gz to compress folder with backed up files:
+    tar -czf "${1}.tar.gz" "${1}"
+    # store error, to be able to print error message:
+    [[ $? -eq 0 ]] || compress_error="1"
+  fi
+  [[ "${compress_error}" == "1" ]] && printf "\n%s\n" "-- ERROR: Compressing the files produced an error. See lines right above."
+
+  # move compressed backup to backup directory:
+  mv "${1}.${compression_method}" "${backup_dir}/"
+
+  # remove original (uncompressed) files:
+  rm -r "${1}"
+}
+
+backup_database() {
+# creates a backup of Nextclouds database tables
+
+  local dbtype dbhost dbprotocol dbname dbuser dbpassword PGPASSWORD
+
+  printf "%s" "+  backing up database... "
+
+  # first we need to find out which type of database is used (SQLite3, MySQL/MariaDB, PostgreSQL)
+  dbtype="$(get_nc_config_value "dbtype")"
+
+  if [[ "$dbtype" != "sqlite3" ]]; then
+    # if database is not SQLite3 - we also need more things to know (dbhost, dbname, dbuser, dbpassword)
+    dbhost="$(get_nc_config_value "dbhost")"
+    dbname="$(get_nc_config_value "dbname")"
+    dbuser="$(get_nc_config_value "dbuser")"
+    dbpassword="$(get_nc_config_value "dbpassword")"
+
+    # check whether dbhost contains socket (e.g. 'localhost:/path/to/socket') or portnumber (e.g. 'localhost:3306')
+    #   and store it for commands:
+    if [[ "${dbhost}" =~ ^.+:/.+$ ]]; then
+      # dbhost contains socket after hostname (e.g. 'localhost:/var/run/mysqld/mysqld.sock'):
+      if [[ "${dbtype}" == "mysql" ]]; then
+        # specify socket and host for MySQL/MariaDB
+        dbprotocol="--socket=${dbhost#*:}"
+        dbhost="${dbhost%%:*}"
+      elif [[ "${dbtype}" == "pgsql" ]]; then
+        # use socket as host for PostgreSQL - see: https://www.postgresql.org/docs/current/static/app-pgdump.html:
+        dbprotocol=""
+        dbhost="${dbhost#*:}"
+      fi
+    elif [[ "${dbhost}" =~ ^.+:[[:digit:]]+$ ]]; then
+      # dbhost contains portnumber after hostname (e.g. '127.0.0.1:3306'):
+      dbprotocol="--port=${dbhost#*:}"
+      dbhost="${dbhost%%:*}"
+    else
+      # dbhost contains only hostname - use empty value to tell database-command to use default value:
+      dbprotocol=""
+    fi
+
+    if [[  "$dbtype" == "mysql" ]]; then
+      # dump MySQL/MariaDB database:
+      mysqldump --single-transaction -h ${dbhost} ${dbprotocol} -u ${dbuser} -p${dbpassword} ${dbname} > "${temp_dir}/nextcloud-sqlbkp_${now}.bak"
+    elif [[ "$dbtype" == "pgsql" ]]; then
+      # dump PostgreSQL database:
+      PGPASSWORD="${dbpassword}" pg_dump ${dbname} -h ${dbhost} ${dbprotocol} -U ${dbuser} -f "${temp_dir}/nextcloud-sqlbkp_${now}.bak"
+    fi
+
+  elif [[ "$dbtype" == "sqlite3" ]]; then
+    # SQLite3 database is located in data directory. Let's find out where that is:
+    nc_data_dir="$(get_nc_config_value "datadirectory")"
+    # dump sqlite3 database:
+    sqlite3 ${nc_data_dir}/owncloud.db .dump > "${temp_dir}/nextcloud-sqlbkp_${now}.bak"
+  fi
+
+  # compress database backup and move it to backup folder:
+  compress_move_backup "nextcloud-sqlbkp_${now}.bak"
+
+  printf "%s\n" "done!"
 }
 
 download_archive() {
@@ -207,7 +318,6 @@ rename_old_nextcloud() {
 # adds current date and time to old Nextcloud folder to keep it as backup
 
   echo "+  renaming old Nextcloud folder by adding current date and time to foldername"
-  now=$(date +"%Y.%m.%d-%H.%M")
   mv "${nextcloud_dir}" "${nextcloud_dir}_${now}"
 }
 
@@ -253,6 +363,8 @@ ask_for_version
 read_configfile
 maintenance_mode "on"
 create_temp_dir
+create_backup_dir
+backup_database
 download_archive
 verify_checksum
 verify_signature
