improve error handling for canonicalizing path

diff --git a/ncupgrade b/ncupgrade
--- a/ncupgrade
+++ b/ncupgrade
@@ -25,7 +25,7 @@ set -euo pipefail
 # set -x
 
 # ncupgrade version:
-ncupgrade_version="0.3.1-1 (07.06.2018), AGPL-3.0"
+ncupgrade_version="0.3.1-2 (07.06.2018), AGPL-3.0"
 
 ###
 ### BEGIN: FUNCTION DEFINITIONS
@@ -246,16 +246,13 @@ get_absolute_path() {
 # this needs to be done because the script changes directories
 # arguments: ${1}=directory; ${2}=path to file (relative to ${1} or absolute)
 
+  local absolute_path
   if [[ "${2}" != /* ]]; then
     # change path of ${2} (file) relative to ${1} (dir) to absolute path and remove trailing slashes:
-    local absolute_path="$(readlink -f "${1}/${2}")"
-    # error and exit if readlink could not canonicalize the given path and did return nothing:
-    [[ "${absolute_path}" == "" ]] && error_exit "ERROR: path '${1}/${2}' can't be canonicalized" "Check given path!"
+    absolute_path="$(readlink -f "${1}/${2}")" || error_exit "ERROR: path '${1}/${2}' can't be canonicalized" "Check given path!"
   else
     # if ${2} contains already absolute path, then only remove trailing slashes:
-    local absolute_path="$(readlink -f "${2}")"
-    # error and exit if readlink could not canonicalize the given path and did return nothing:
-    [[ "${absolute_path}" == "" ]] && error_exit "ERROR: path '${2}' can't be canonicalized" "Check given path!"
+    absolute_path="$(readlink -f "${2}")" || error_exit "ERROR: path '${2}' can't be canonicalized" "Check given path!"
   fi
   echo "${absolute_path}"
 }
